export const Modules = [
  {
    id: 1,
    name: 'Верхняя балка',
    price: '7200',
    iamge: '1.png',
  },
  {
    id: 2,
    name: 'Верхняя балка с лого',
    price: '10500',
    iamge: '2.png',
  },
  {
    id: 3,
    name: 'Турник',
    price: '1800',
    iamge: '3.png',
  },
  {
    id: 4,
    name: 'Турник разнохват ',
    price: '4000',
    iamge: '4.png',
  },
  {
    id: 5,
    name: 'Модуль заднего ГП 80 кг',
    price: '79600',
    iamge: '5.png',
  },
  {
    id: 6,
    name: 'Модуль заднего ГП (свободный вес)',
    price: '44800',
    iamge: '6.png',
  },
  {
    id: 7,
    name: 'Модуль бокового ГП 80кг',
    price: '69900',
    iamge: '7.png',
  },
  {
    id: 8,
    name: 'Модуль бокового ГП (свободный вес)',
    price: '38900',
    iamge: '8.png',
  },
  {
    id: 9,
    name: 'Крюк для грифа',
    price: '5000',
    iamge: '9.png',
  },
  {
    id: 10,
    name: 'Страховочная балка внутренняя',
    price: '12000',
    iamge: '10.png',
  },
  {
    id: 11,
    name: 'Страховочная балка наружная',
    price: '12000',
    iamge: '11.png',
  },
  {
    id: 12,
    name: 'Платформа',
    price: '15000',
    iamge: '12.png',
  },
  {
    id: 13,
    name: 'Подушка для платформы',
    price: '6600',
    iamge: '13.png',
  },
  {
    id: 14,
    name: 'Фиксатор',
    price: '600',
    iamge: '14.png',
  },
  {
    id: 15,
    name: 'Фиксатор + шплинт',
    price: '650',
    iamge: '15.png',
  },
  {
    id: 16,
    name: 'Фиксатор жгутов',
    price: '750',
    iamge: '16.png',
  },
  {
    id: 17,
    name: 'Поворотный модуль',
    price: '15000',
    iamge: '17.png',
  },
  {
    id: 18,
    name: 'Ручка с дискодержателем',
    price: '4000',
    iamge: '18.png',
  },
  {
    id: 19,
    name: 'Тяга грифа',
    price: '1500',
    iamge: '19.png',
  },
  {
    id: 20,
    name: 'Держатель грифа',
    price: '1500',
    iamge: '20.png',
  },
  {
    id: 21,
    name: 'Брусья',
    price: '12000',
    iamge: '21.png',
  },
  {
    id: 22,
    name: 'Валик 400',
    price: '3500',
    iamge: '22.png',
  },
  {
    id: 23,
    name: 'Фиксатор жгутов',
    price: '',
    iamge: undefined,
  },
  {
    id: 24,
    name: 'Дискодержатель 200',
    price: '2500',
    iamge: '24.png',
  },
  {
    id: 25,
    name: 'Дискодержатель 350',
    price: '3000',
    iamge: '25.png',
  },
  {
    id: 26,
    name: 'Тяга широкая',
    price: '1500',
    iamge: '26.png',
  },
  {
    id: 27,
    name: 'Тяга 2 руками узкий хват',
    price: '1200',
    iamge: '27.png',
  },
  {
    id: 28,
    name: 'W - Ручка',
    price: '1400',
    iamge: '28.png',
  },
  {
    id: 29,
    name: 'Ручка короткая',
    price: '',
    iamge: '29.png',
  },
  {
    id: 30,
    name: 'Ручка одинарная',
    price: '',
    iamge: undefined,
  },
  {
    id: 31,
    name: 'Ручка одинарная мягкая',
    price: '',
    iamge: undefined,
  },
  {
    id: 32,
    name: 'Ручка короткая',
    price: '',
    iamge: '32.png',
  },
  {
    id: 33,
    name: 'Ручка широкая',
    price: '',
    iamge: undefined,
  },
  {
    id: 34,
    name: 'Тяга 2 руками широкий хват',
    price: '',
    iamge: undefined,
  },
  {
    id: 35,
    name: 'Скамья универсальная (карбон)',
    price: '30000',
    iamge: '35.png',
  },
  {
    id: 36,
    name: 'Скамья универсальная',
    price: '25000',
    iamge: '36.png',
  },
];
